// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var _isIEMobile, _isIpad, _isMobile, _isWebKit, contains, detekt, parser, ua;
  parser = require('ua-parser');
  contains = require('underscore').contains;
  ua = null;
  _isIpad = function () {
    return /iPad/.test(parser.parseDevice(ua).toString());
  };
  _isMobile = function () {
    return /Mobile\b/.test(ua);
  };
  _isWebKit = function () {
    return /\bAppleWebKit\b/.test(ua);
  };
  _isIEMobile = function () {
    return /IE Mobile/.test(parser.parseUA(ua).toString());
  };
  detekt = {
    isTouchSupported: function (userAgent) {
      ua = userAgent;
      return _isIEMobile() || !_isIpad() && _isWebKit() && _isMobile();
    }
  };
  module.exports = detekt;
}.call(this);
