// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var _isAndroidTab, _isIEMobile, _isIpad, _isMobile, _isWebKit, contains, detekt, parser, ua;
  parser = require('ua-parser');
  contains = require('underscore').contains;
  ua = null;
  _isIpad = function () {
    return /iPad/.test(parser.parseDevice(ua).toString());
  };
  _isMobile = function () {
    return /Mobile\b/.test(ua);
  };
  _isWebKit = function () {
    return /\bAppleWebKit\b/.test(ua);
  };
  _isIEMobile = function () {
    return /IE Mobile/.test(parser.parseUA(ua).toString());
  };
  _isAndroidTab = function () {
    return /Android.*AppleWebKit.*(?!Mobile)/.test(ua);
  };
  detekt = {
    isTouchSupported: function (userAgent) {
      ua = userAgent;
      return _isIEMobile() || !_isIpad() && _isWebKit() && _isMobile();
    },
    isPlatform: function (userAgent, platform) {
      var re;
      re = new RegExp(platform, 'i');
      return re.test(parser.parseOS(userAgent));
    },
    isiOS: function (userAgent) {
      return this.isPlatform(userAgent, 'iOS');
    },
    isAndroid: function (userAgent) {
      return this.isPlatform(userAgent, 'Android');
    },
    isWindowsPhone: function (userAgent) {
      return this.isPlatform(userAgent, 'Windows Phone');
    },
    isDevice: function (userAgent, device) {
      var re;
      re = new RegExp(device, 'i');
      return re.test(parser.parseDevice(userAgent).toString());
    },
    isMobile: function (userAgent) {
      ua = userAgent;
      return _isMobile() && !_isIpad();
    },
    isTablet: function (userAgent) {
      ua = userAgent;
      return _isIpad() || _isAndroidTab();
    }
  };
  module.exports = detekt;
}.call(this);
