// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var _blacklisted, _blacklistedDevices, contains, detekt, parser;
  parser = require('ua-parser');
  contains = require('underscore').contains;
  _blacklistedDevices = [
    'iPad',
    'Other'
  ];
  _blacklisted = function (ua) {
    console.log(parser.parseDevice(ua).toString());
    return contains(_blacklistedDevices, parser.parseDevice(ua).toString());
  };
  detekt = {
    isTouchSupported: function (userAgent) {
      return !_blacklisted(userAgent);
    }
  };
  module.exports = detekt;
}.call(this);
